version: '2.1'

services:
  tsdb:
    image: jsvisa/ethereum-tsdb:latest
    container_name: tsdb
    deploy:
      resources:
        limits:
          memory: 30G
        reservations:
          memory: 2G
    command:
      - 'postgres'
      - '-cshared_preload_libraries=pg_stat_statements'
      - '-cshared_preload_libraries=timescaledb'
      - '-cmax_connections=1000'
      - '-cmax_wal_size=8GB'
      - '-cshared_buffers=20GB'
      - '-clisten_addresses="*"'
      - '-cwal_level=replica'
      - '-cmax_wal_senders=2'
      - '-cmax_replication_slots=2'
      - '-csynchronous_commit=off'
    volumes:
      - ./pgdata:/home/postgres/pgdata
      - ./pg_log:/home/postgres/pg_log
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tsdb
    restart: unless-stopped
    ports:
      - '5432:5432'

  pgcat:
    image: ghcr.io/postgresml/pgcat:latest
    container_name: pgcat
    command:
      - 'pgcat'
      - '/etc/pgcat/pgcat.toml'
    volumes:
      - ./etc/pgcat.toml:/etc/pgcat/pgcat.toml
    restart: unless-stopped
    ports:
      - '6432:6432'
      - '9930:9930'
