#!/usr/bin/env python3

import sys
import json
from datetime import datetime
import requests

if len(sys.argv) == 1:
    print(f"Usage {sys.argv[0]} <endpoint> <blknum>")
    sys.exit(1)

if len(sys.argv) > 1:
    endpoint = sys.argv[1]
else:
    endpoint = "http://127.0.0.1:4545"

if len(sys.argv) > 2:
    blknum = sys.argv[2]
else:
    blknum = "latest"

if blknum.isdigit():
    blknum = hex(int(blknum))

res = requests.post(
    endpoint,
    json=dict(
        method="eth_getBlockByNumber", id=1, jsonrpc="2.0", params=[blknum, False]
    ),
).json()

result = res["result"]

if result is None:
    resp = {"blknum": 0, "timestamp": 0}
else:
    resp = {
        "blknum": int(result["number"], 16),
        "timestamp": str(datetime.utcfromtimestamp(int(result["timestamp"], 16))),
    }

print(json.dumps(resp))
